.PHONY: all a4 all-formats check check-a4 site stubs-check en pl en-a4 pl-a4 \
        text-only watch-en watch-pl clean diagrams diagrams-clean \
        numbers verify stubs answers frames outcomes values translate shots debt

# Two paper formats from one source. `standard` is the 17 x 24 cm trade format
# shared with the companion volumes; `a4` is A4 at 12pt, which is what the book
# is actually read in -- on a screen, or off an office printer. The format is
# chosen by the main file, and the four main files differ in five lines.
LANGS   := en pl
FORMATS := standard a4

MMD_SRC := $(wildcard figures/mermaid/en/*.mmd) $(wildcard figures/mermaid/pl/*.mmd)
MMD_PDF := $(patsubst figures/mermaid/%.mmd,figures/diagrams/%.pdf,$(MMD_SRC))
VAL_SRC := $(wildcard code/*.py)

# mermaid-cli drives a headless Chromium. The config below is written on first
# use and points at whatever browser is available; override BROWSER on the
# command line if yours lives somewhere else.
BROWSER ?= $(shell command -v chromium 2>/dev/null || command -v chromium-browser 2>/dev/null || command -v google-chrome 2>/dev/null || echo /opt/pw-browsers/chromium)

all: numbers diagrams en pl check

# Both editions on A4. Use `make all-formats` for all four PDFs.
a4: numbers diagrams en-a4 pl-a4 check-a4

all-formats: numbers diagrams en pl en-a4 pl-a4 check check-a4

# The three gates. A build that only *looked* like it succeeded is the failure
# mode this book cannot afford: -interaction=nonstopmode writes a PDF over the
# top of an error, and with -file-line-error the error line does not begin with
# a `!`, so the inherited `grep '^!' main.log` habit cannot see it.
check:
	@python3 tools/gen_stubs.py --check
	@python3 tools/checklog.py main-en.log main-pl.log
	@python3 tools/checkpdf.py main-en.pdf main-pl.pdf
	@python3 tools/parity.py | tail -n 3
	@python3 tools/reflist.py 2>/dev/null || true

# The A4 build is the same source, so parity and the stub manifest are already
# covered by `check`. What is NOT covered is the log: a format change can push
# a table past a page boundary and produce an overfull vbox in one format only,
# which is exactly the class of defect the trade format's own log cannot see.
check-a4:
	@python3 tools/checklog.py main-en-a4.log main-pl-a4.log
	@python3 tools/checkpdf.py main-en-a4.pdf main-pl-a4.pdf

en: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-en.tex
	@python3 tools/checklog.py main-en.log

pl: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-pl.tex
	@python3 tools/checklog.py main-pl.log

en-a4: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-en-a4.tex
	@python3 tools/checklog.py main-en-a4.log

pl-a4: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-pl-a4.tex
	@python3 tools/checklog.py main-pl-a4.log

# Skip diagram rendering and value regeneration -- useful when iterating on
# prose. Unrendered diagrams print their Mermaid source, so the build is still
# readable, and a stale value still prints; it is the CI job that catches drift.
text-only:
	latexmk -pdf -interaction=nonstopmode main-en.tex
	latexmk -pdf -interaction=nonstopmode main-pl.tex

# Assemble locally exactly what CI publishes to Pages, so a link or a layout
# change can be checked before it is deployed rather than after.
site: en pl en-a4 pl-a4
	@rm -rf _site && mkdir -p _site
	@cp -r docs/. _site/
	@cp main-en.pdf "_site/Mathematics-from-Zero-for-the-AI-Engineer.pdf"
	@cp main-pl.pdf "_site/Matematyka-od-zera-dla-inzyniera-AI.pdf"
	@cp main-en.pdf _site/book-en.pdf
	@cp main-pl.pdf _site/book-pl.pdf
	@cp main-en-a4.pdf _site/book-en-a4.pdf
	@cp main-pl-a4.pdf _site/book-pl-a4.pdf
	@echo "  _site/ assembled. Open _site/index.html."

watch-en:
	latexmk -pvc -pdf -interaction=nonstopmode main-en.tex
watch-pl:
	latexmk -pvc -pdf -interaction=nonstopmode main-pl.tex

clean:
	for j in main-en main-pl main-en-a4 main-pl-a4; do latexmk -C $$j.tex; done
	rm -rf _site
	rm -f *.dgm *.ilg *.ind *.idx programs/*/*.aux appendices/*/*.aux

# ---------------------------------------------------------------------------
# Numbers. Every numeric value in the book is produced here and pulled into the
# text with \val{}. The book does not contain the digits, it contains a
# reference to them, so the book and the scripts cannot disagree.
# ---------------------------------------------------------------------------
numbers:
	@mkdir -p figures/values
	@for f in $(VAL_SRC); do \
	  echo "  values: $$f"; \
	  python3 "$$f" || exit 1; \
	done
	@# One file the preamble can \input, because TeX cannot glob a directory.
	@{ echo '% Generated by `make numbers` --- do not edit.'; \
	   for v in figures/values/*.tex; do \
	     case "$$v" in */all.tex) continue;; esac; \
	     echo "\\input{$${v%.tex}}"; \
	   done; } > figures/values/all.tex
	@echo "  index:  figures/values/all.tex"

# Re-runs the scripts and fails if any committed value would change. This is
# the check that makes the previous rule mean something.
# TWO failures, not one, and `git diff` alone can only see the first.
#
#   drift     -- a tracked value file no longer matches its script
#   untracked -- a value file git has never seen, so it was never compared to
#                anything. Every program's FIRST values file is in this state,
#                which means every program's first values file used to pass
#                this gate by being invisible to it. Found when F02 added 32
#                values and the gate went green on all of them.
#
# Staged-but-not-committed is NOT a failure: the content matches the script,
# which is the whole question this gate asks. Testing `git status --porcelain`
# instead would fail on a staged file and make the gate unusable mid-commit.
verify: numbers
	@drift=$$(git diff --name-only -- figures/values); \
	 new=$$(git ls-files --others --exclude-standard -- figures/values); \
	 if [ -n "$$drift" ] || [ -n "$$new" ]; then \
	   [ -n "$$drift" ] && { echo "STALE: these no longer match their script:"; \
	                         echo "$$drift"; git diff --stat -- figures/values; }; \
	   [ -n "$$new" ] && { echo "UNTRACKED: git has never seen these, so they have"; \
	                       echo "never been compared to anything. git add them:"; \
	                       echo "$$new"; }; \
	   exit 1; \
	 else echo "All computed values are current."; fi

# ---------------------------------------------------------------------------
# Diagrams. Source of truth is figures/mermaid/<lang>/*.mmd, committed. The
# rendered PDFs are build output and are gitignored, so a diagram change shows
# up in review as a readable text diff.
# ---------------------------------------------------------------------------
diagrams: $(MMD_PDF)

figures/diagrams/%.pdf: figures/mermaid/%.mmd figures/mermaid/.puppeteer.json figures/mermaid/config.json
	@mkdir -p $(dir $@)
	npx -y @mermaid-js/mermaid-cli@11 \
	  -i $< -o $@ \
	  -p figures/mermaid/.puppeteer.json \
	  -c figures/mermaid/config.json \
	  -b transparent --pdfFit

figures/mermaid/.puppeteer.json:
	@mkdir -p figures/mermaid
	@printf '{"executablePath":"%s","args":["--no-sandbox","--disable-dev-shm-usage"]}\n' "$(BROWSER)" > $@
	@echo "Wrote $@ pointing at $(BROWSER)"

diagrams-clean:
	rm -rf figures/diagrams

# ---------------------------------------------------------------------------
# Debt ledgers. Each is a promise made to a reader that has not yet been kept,
# so it is counted rather than remembered. Four of these are new to this book;
# the other three are inherited from the companion volumes.
# ---------------------------------------------------------------------------

# 0. The manifest and the tree agree. tools/programs.json is the single source
#    of the part and program sequence; this fails when a stub or structure.tex
#    is stale against it.
stubs-check:
	@python3 tools/gen_stubs.py --check

# 1. Programs not yet written.
stubs:
	@for L in $(LANGS); do \
	  n=$$(grep -rl '\\programstub{' programs/$$L 2>/dev/null | wc -l); \
	  echo "  $$L: $$n of $$(ls programs/$$L/*.tex 2>/dev/null | wc -l) programs are stubs"; \
	done

# 2. Exercises with no answer. A mathematics book's most common defect, and
#    mechanically detectable.
answers:
	@python3 tools/check_structure.py --answers

# 3. Frame counts against the 30--70 band, and frames that ask a question
#    nobody answers.
frames:
	@python3 tools/check_structure.py --frames

# 4. Programs that declare no learning outcomes. The "Can you?" checklist is
#    GENERATED from the outcomes, so it can no longer drift from them -- which
#    means the only failure left is a program that declared none at all.
outcomes:
	@python3 tools/check_structure.py --outcomes

# 5. \val{} references with no value behind them, and values nothing uses.
values:
	@python3 tools/check_structure.py --values

# 6. The two editions out of step. tools/parity.py is the single parity tool;
#    it compares an ORDERED structural signature rather than counts, because a
#    histogram cannot see \yourturn moving from frame 2 to frame 3, and every
#    Summary back-reference and Quiz route navigates by frame number.
translate:
	@python3 tools/parity.py | tail -n 3
	@python3 tools/reflist.py 2>/dev/null || \
	  echo "  (cross-reference comparison needs a completed build of both editions)"

# 7. Numeric claims not produced by a script, and diagrams not drawn.
shots:
	@printf "  verifybox blocks: "
	@grep -rc 'begin{verifybox}' programs appendices 2>/dev/null \
	  | awk -F: '{s+=$$2} END {print s+0}'
	@printf "  mermaid sources:  "
	@ls figures/mermaid/*/*.mmd 2>/dev/null | wc -l

debt:
	@echo "== Manifest and tree =="              ; $(MAKE) -s stubs-check || true
	@echo; echo "== Programs not yet written ==" ; $(MAKE) -s stubs
	@echo; echo "== Exercises with no answer =="  ; $(MAKE) -s answers
	@echo; echo "== Frames =="                    ; $(MAKE) -s frames
	@echo; echo "== Learning outcomes =="         ; $(MAKE) -s outcomes
	@echo; echo "== Computed values =="           ; $(MAKE) -s values
	@echo; echo "== Polish/English parity =="     ; $(MAKE) -s translate
	@echo; echo "== Unverified claims, diagrams ="; $(MAKE) -s shots
	@echo
	@echo "== Reader validation =="
	@echo "  80/80: NOT ESTABLISHED. The method is validated; this book is not."
	@echo "  It may not claim 80/80 until it has been trialled on readers."
	@echo
	@echo "  The instrument is the scored Test exercises, NOT the Quiz. The Quiz"
	@echo "  runs on the thirteen Foundation programs only, so a standard defined"
	@echo "  against it would be unmeasurable on thirty-four of the forty-seven --"
	@echo "  and contaminated on the other thirteen, because the same items are"
	@echo "  used on entry and on exit. Every program has Test exercises."
