.PHONY: all en pl text-only watch-en watch-pl clean diagrams diagrams-clean \
        numbers verify stubs answers frames outcomes values translate shots debt

LANGS   := en pl
MMD_SRC := $(wildcard figures/mermaid/en/*.mmd) $(wildcard figures/mermaid/pl/*.mmd)
MMD_PDF := $(patsubst figures/mermaid/%.mmd,figures/diagrams/%.pdf,$(MMD_SRC))
VAL_SRC := $(wildcard code/*.py)

# mermaid-cli drives a headless Chromium. The config below is written on first
# use and points at whatever browser is available; override BROWSER on the
# command line if yours lives somewhere else.
BROWSER ?= $(shell command -v chromium 2>/dev/null || command -v chromium-browser 2>/dev/null || command -v google-chrome 2>/dev/null || echo /opt/pw-browsers/chromium)

all: numbers diagrams en pl

en: numbers
	latexmk -pdf -interaction=nonstopmode main-en.tex

pl: numbers
	latexmk -pdf -interaction=nonstopmode main-pl.tex

# Skip diagram rendering and value regeneration -- useful when iterating on
# prose. Unrendered diagrams print their Mermaid source, so the build is still
# readable, and a stale value still prints; it is the CI job that catches drift.
text-only:
	latexmk -pdf -interaction=nonstopmode main-en.tex
	latexmk -pdf -interaction=nonstopmode main-pl.tex

watch-en:
	latexmk -pvc -pdf -interaction=nonstopmode main-en.tex
watch-pl:
	latexmk -pvc -pdf -interaction=nonstopmode main-pl.tex

clean:
	latexmk -C main-en.tex; latexmk -C main-pl.tex
	rm -f *.dgm *.ilg *.ind *.idx programs/*/*.aux appendices/*/*.aux

# ---------------------------------------------------------------------------
# Numbers. Every numeric value in the book is produced here and pulled into the
# text with \val{}. The book does not contain the digits, it contains a
# reference to them, so the book and the scripts cannot disagree.
# ---------------------------------------------------------------------------
numbers:
	@mkdir -p figures/values
	@for f in $(VAL_SRC); do \
	  echo "  values: $$f"; \
	  python3 "$$f" || exit 1; \
	done
	@# One file the preamble can \input, because TeX cannot glob a directory.
	@{ echo '% Generated by `make numbers` --- do not edit.'; \
	   for v in figures/values/*.tex; do \
	     case "$$v" in */all.tex) continue;; esac; \
	     echo "\\input{$${v%.tex}}"; \
	   done; } > figures/values/all.tex
	@echo "  index:  figures/values/all.tex"

# Re-runs the scripts and fails if any committed value would change. This is
# the check that makes the previous rule mean something.
verify: numbers
	@git diff --quiet -- figures/values 2>/dev/null \
	  && echo "All computed values are current." \
	  || { echo "STALE: figures/values differs from what the scripts now produce."; \
	       git diff --stat -- figures/values; exit 1; }

# ---------------------------------------------------------------------------
# Diagrams. Source of truth is figures/mermaid/<lang>/*.mmd, committed. The
# rendered PDFs are build output and are gitignored, so a diagram change shows
# up in review as a readable text diff.
# ---------------------------------------------------------------------------
diagrams: $(MMD_PDF)

figures/diagrams/%.pdf: figures/mermaid/%.mmd figures/mermaid/.puppeteer.json figures/mermaid/config.json
	@mkdir -p $(dir $@)
	npx -y @mermaid-js/mermaid-cli@11 \
	  -i $< -o $@ \
	  -p figures/mermaid/.puppeteer.json \
	  -c figures/mermaid/config.json \
	  -b transparent --pdfFit

figures/mermaid/.puppeteer.json:
	@mkdir -p figures/mermaid
	@printf '{"executablePath":"%s","args":["--no-sandbox","--disable-dev-shm-usage"]}\n' "$(BROWSER)" > $@
	@echo "Wrote $@ pointing at $(BROWSER)"

diagrams-clean:
	rm -rf figures/diagrams

# ---------------------------------------------------------------------------
# Debt ledgers. Each is a promise made to a reader that has not yet been kept,
# so it is counted rather than remembered. Four of these are new to this book;
# the other three are inherited from the companion volumes.
# ---------------------------------------------------------------------------

# 1. Programs not yet written.
stubs:
	@for L in $(LANGS); do \
	  n=$$(grep -rl '\\programstub{' programs/$$L 2>/dev/null | wc -l); \
	  echo "  $$L: $$n of $$(ls programs/$$L/*.tex 2>/dev/null | wc -l) programs are stubs"; \
	done

# 2. Exercises with no answer. A mathematics book's most common defect, and
#    mechanically detectable.
answers:
	@python3 tools/check_structure.py --answers

# 3. Frame counts against the 30--70 band, and frames that ask a question
#    nobody answers.
frames:
	@python3 tools/check_structure.py --frames

# 4. Programs that declare no learning outcomes. The "Can you?" checklist is
#    GENERATED from the outcomes, so it can no longer drift from them -- which
#    means the only failure left is a program that declared none at all.
outcomes:
	@python3 tools/check_structure.py --outcomes

# 5. \val{} references with no value behind them, and values nothing uses.
values:
	@python3 tools/check_structure.py --values

# 6. The two editions out of step.
translate:
	@python3 tools/check_parity.py

# 7. Numeric claims not produced by a script, and diagrams not drawn.
shots:
	@printf "  verifybox blocks: "
	@grep -rc 'begin{verifybox}' programs appendices 2>/dev/null \
	  | awk -F: '{s+=$$2} END {print s+0}'
	@printf "  mermaid sources:  "
	@ls figures/mermaid/*/*.mmd 2>/dev/null | wc -l

debt:
	@echo "== Programs not yet written =="        ; $(MAKE) -s stubs
	@echo; echo "== Exercises with no answer =="  ; $(MAKE) -s answers
	@echo; echo "== Frames =="                    ; $(MAKE) -s frames
	@echo; echo "== Learning outcomes =="         ; $(MAKE) -s outcomes
	@echo; echo "== Computed values =="           ; $(MAKE) -s values
	@echo; echo "== Polish/English parity =="     ; $(MAKE) -s translate
	@echo; echo "== Unverified claims, diagrams ="; $(MAKE) -s shots
	@echo
	@echo "== Reader validation =="
	@echo "  80/80: NOT ESTABLISHED. The method is validated; this book is not."
	@echo "  It may not claim 80/80 until it has been trialled on readers."
