flowchart LR
  A["dwa rownania o x i y to<br/>dwie proste na jednej kartce"]
  A --> B["rozne wspolczynniki kierunkowe?<br/>przecinaja sie dokladnie raz,<br/>a ten punkt jest rozwiazaniem"]
  B --> C["rowne wspolczynniki?<br/>albo zaden punkt nie lezy na obu,<br/>albo lezy na obu kazdy"]
