flowchart LR
  A["wybierz dwa punkty na krzywej i polacz<br/>je: ta prosta ma nachylenie"]
  A --> B["przesuwaj drugi punkt ku pierwszemu,<br/>a nachylenie sie zmienia"]
  B --> C["liczba, na ktorej sie zatrzymuje,<br/>to pochodna"]
