flowchart LR
  A["pelna aktualizacja jest tak szeroka i wysoka<br/>jak warstwa i kosztuje tyle samo liczb"]
  A --> B["zapisanie jej jako dwoch chudych czynnikow<br/>ogranicza liczbe kierunkow, w ktore moze isc"]
  B --> C["oszczednoscia jest to ograniczenie, a ono jest<br/>zalozeniem o aktualizacji, a nie faktem"]
