flowchart LR
  A["graf to dwa zbiory: obiekty oraz te ich pary,<br/>ktore sa polaczone. Nic wiecej nie potrzeba"]
  A --> B["pary UPORZADKOWANE czynia go skierowanym, wiec<br/>wywolania, importy i zaleznosci maja ten sam ksztalt"]
  B --> C["kazde pytanie o graf jest wtedy pytaniem<br/>o te relacje i o nic innego"]
