flowchart LR
  A["twierdzenie to zalozenia, teza i kwantyfikatory<br/>mowiace, po czym kazde z nich przebiega"]
  A --> B["teze ludzie cytuja, a zalozenia gubia po drodze,<br/>i to jest cala tresc wiekszosci naduzyc"]
  B --> C["czytanie twierdzenia to rozbieranie go: co sie<br/>zaklada, co orzeka i po czym kazde z tego biegnie"]
