graph LR
  A["jeden cel, dwa garby,<br/>dodatni w kazdym przedziale"] --> B["81 kandydatow,<br/>kazdy oceniony,<br/>bez optymalizatora"]
  B --> C["kazdy cel zwraca<br/>najlepszego ze wszystkich,<br/>a te dwa sie nie zgadzaja"]
