graph LR
  A["suma biegnie po wynikach,<br/>ktore wazy PIERWSZY argument"] --> B["pierwszy mowi, gdzie patrzec,<br/>a drugi jest tam oceniany"]
  B --> C["luka w drugim tam,<br/>gdzie pierwszy ma wage:<br/>w jedna strone nieskonczona, w druga jej nie ma"]
