graph LR
  A["slowo odleglosc obiecuje<br/>symetrie, regule trojkata<br/>i wartosc skonczona"] --> B["ta wielkosc zachowuje<br/>nieujemnosc<br/>i zero tylko przy zgodzie"]
  B --> C["i dlatego nosi<br/>nazwe dywergencji"]
