graph LR
  A["ile kosztuje kod:<br/>dlugosc kazdego slowa,<br/>wazona tym, jak czesto<br/>trafia sie jego symbol"] --> B["podloga:<br/>wlasna entropia zrodla,<br/>do ktorej zaden kod<br/>o calkowitych dlugosciach<br/>nie siega"]
  B --> C["co zostaje:<br/>wielkosc sama w sobie,<br/>ktora ma nazwe"]
