graph LR
  A["jeden blok"] --> B["uwaga:<br/>cztery rzutowania,<br/>4 d kwadrat"]
  A --> C["warstwa gesta:<br/>dwie warstwy, d do 4d<br/>i z powrotem, 8 d kwadrat"]
  B --> D["12 d kwadrat na blok,<br/>i kazda warstwa stosu<br/>placi to jeszcze raz"]
  C --> D
