graph LR
  A["wektor jednej pozycji,<br/>szerokosc d"] --> B["trzy rzutowania:<br/>zapytanie, klucz,<br/>wartosc"]
  B --> C["jeden iloczyn skalarny<br/>na kazda pare pozycji:<br/>jest ich n do kwadratu"]
