graph LR
  A["siedem punktow na trzech<br/>dekadach i prosta przez nie<br/>na osiach log-log"] --> B["WEWNATRZ zakresu: dopasowanie<br/>nie mija zadnego punktu<br/>nawet o pol procenta"]
  A --> C["POZA nim: blad rosnie<br/>z kazda dekada, az prosta<br/>przewiduje strate ponizej podlogi"]
  B --> D["jedna prosta, a te dwie<br/>polowy nie sa twierdzeniami<br/>tego samego rodzaju"]
  C --> D
