graph LR
  A["model sedziujacy ocenia<br/>dwiema stopami, nie jedna:<br/>jak traktuje odpowiedz dobra<br/>i jak traktuje bledna"] --> B["roznica, ktora raportuje<br/>miedzy dwoma modelami, to ich<br/>prawdziwa roznica razy jedna<br/>stala, bez wzgledu na wyniki"]
  B --> C["kurczy wiec sile efektu,<br/>zamiast dodawac do niej szum,<br/>a zgodnosc z jego karty wiaze<br/>inna kombinacje tych stop"]
