graph LR
  A["wynik testu to oszacowanie<br/>skutecznosci na populacji<br/>zadan, na ktorej ci zalezy"] --> B["niesie wiec dwa bledy: los<br/>wybranych pozycji i dystans<br/>miedzy testem a twoim<br/>wlasnym zadaniem"]
  B --> C["pierwszy maleje jak 1/n, a<br/>drugi jest wlasnoscia zbioru;<br/>przedzial w raporcie opisuje<br/>ten pierwszy"]
