"""P33 --- Anatomy of a training run.

Every number Program P33 prints, and the assertions that keep them honest.

PART IX'S CONTRACT IS THAT IT INTRODUCES NO NEW MATHEMATICS, so the first
question was P32's: not "what is left of the subject" but "which lines of the
brief have already been delivered".  `grep -rn 'prog:P33' programs/en/*.tex`
answers it, and the answer is unusually clean -- only F03 defers here, twice,
and both deferrals are exactly the two halves the brief calls this program's
own:

  F03  "Program P33 reads a loss curve as evidence -- what a plateau, a spike
       and a suspiciously smooth descent each imply, and which of them are
       distinguishable from noise."  It owns the log axis and stops there.
  F03  "Program P33 treats such a fit as an empirical fit with a stated
       extrapolation error rather than as a law of nature."  It owns "a power
       law is a straight line on log-log axes and the gradient is the
       exponent" and never fits one.

The SIX bracketed items in the brief are spent by construction, each by a
program whose own header says so:

  P26 the loss as maximum likelihood      P18 its gradient as p - y
  P20 the optimiser (F04 owns the average and the bias correction)
  P01 precision, and P20 loss scaling     P17 eta < 2/lambda_max
  F06 clipping outright, P21 the noise model behind it

So this program re-teaches none of them.  It assembles them, and then asks the
one question the assembly makes available and no owner could: OF THE SIX,
WHICH FAIL SILENTLY?  Four do, and all four show up on the loss curve -- which
is what makes section 2 a reading of evidence rather than a gallery of shapes.

METHOD, from P30, P31 and P32: derive in closed form wherever possible,
because a demonstration whose answer depends on a seed measures the sampler.
NOTHING HERE IS SAMPLED.  The plateau, the spike and the smoother are all
exact statements about a normal distribution, computed with math.erf; the
scaling fit is least squares in closed form over data generated from a
relation whose truth is known because this script chose it.

And issue #47 requires that any loss curve shown be generated by a script
rather than drawn.  It is -- and generating it needs NO trained model, which
is P32's split asked of this program's own claims: the shapes are properties
of an optimiser walking a quadratic under minibatch noise, and the book owns
the optimiser (P20), the quadratic (P17, P10) and the noise (P21).

Run:  python3 code/p33_training_run.py
"""

from __future__ import annotations

import math
import re
from fractions import Fraction
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "figures" / "values" / "p33.tex"
TRANSCRIPT = OUT.parent.parent / "transcripts"
VALUES: dict[str, tuple[str, bool]] = {}


def emit(key: str, value, digits: int | None = None) -> None:
    if isinstance(value, float) and digits is not None:
        body = f"{value:.{digits}f}"
    elif isinstance(value, float):
        body = repr(value)
    else:
        body = str(value)
    try:
        numeric = math.isfinite(float(body.replace("e", "E")))
    except ValueError:
        numeric = False
    VALUES[key] = (body, numeric)


def committed(fname: str, key: str) -> str | None:
    """Another program's committed value, read back so the two cannot drift."""
    path = OUT.parent / fname
    if not path.exists():                                    # pragma: no cover
        return None
    m = re.search(r"\\mfaval\{" + re.escape(key) + r"\}\{([^}]*)\}",
                  path.read_text(encoding="utf8"))
    return m.group(1) if m else None


def pct(x: float) -> float:
    """Refuse a percentage that rounds to 0 or 100 and so reads as exact."""
    r = round(x, 1)
    assert r not in (0.0, 100.0), (
        f"{x} rounds to {r} per cent, which reads as exact and is not.")
    return x


def reproduces(value: float, digits: int, *operands, op) -> float:
    """Refuse a quantity that does not come back out of its own printed page."""
    shown = [float(f"{v:.{d}f}") for v, d in operands]
    assert f"{op(*shown):.{digits}f}" == f"{value:.{digits}f}", (
        f"the page prints {value:.{digits}f} beside operands that give "
        f"{op(*shown):.{digits}f}; a reader who checks will find it wrong.")
    return value


def Phi(z: float) -> float:
    """The standard normal distribution function, from the error function."""
    return 0.5 * (1.0 + math.erf(z / math.sqrt(2.0)))


def z_for(tail: float) -> float:
    """The z with an upper tail of `tail`, by bisection.  No library needed."""
    lo, hi = 0.0, 40.0
    for _ in range(200):
        mid = (lo + hi) / 2.0
        if 1.0 - Phi(mid) > tail:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2.0


assert abs(Phi(0.0) - 0.5) < 1e-15
assert abs(z_for(0.025) - 1.959964) < 1e-5, z_for(0.025)


# ======================================================================
# SECTION 1 --- THE RUN AS ONE OBJECT, AND WHICH OF ITS SIX PIECES FAIL
# SILENTLY.
#
# Nothing here is derived.  Every figure is READ BACK from the program that
# owns it, so a correction anywhere in Parts II to VIII stops this program
# rather than quietly leaving it describing a book that has moved.  That is
# the assembly's whole job, and it is also the only honest way for a Part IX
# program to quote six neighbours at once.
#
# The one thing the assembly ADDS is the question no owner could ask: put the
# six in the order they execute and ask which of them, got wrong, raises
# nothing.  Four do not raise, and all four move the loss curve -- which is
# what makes section 2 a reading of evidence rather than a gallery of shapes.
# ======================================================================

# --- the loss (P26, over F02's own committed figure) ---
LOSS_NATS = float(committed("p26.tex", "p26.f02.loss") or 2.4)
emit("p33.loss.nats", LOSS_NATS, 1)

# Its silent failure is P19's: average the per-sequence perplexities instead of
# exponentiating the average loss, and at a per-token spread of 2 the reported
# figure is this many times the true one.  No error, no warning.
PPL_RATIO = float(committed("p19.tex", "p19.ppl.ratio.20") or 7.42)
emit("p33.fail.ppl", PPL_RATIO, 2)

# --- the gradient (P18) ---
# Its failure is LOUD, and that is the point of the contrast: the honest
# two-step route forms -1/p_c, and once a logit falls this far below the
# largest, p_c underflows and it divides by zero.
GRAD_CLIFF = float(committed("p18.tex", "p18.cliff") or -744)
emit("p33.grad.cliff", GRAD_CLIFF, 0)

# --- the optimiser (P20; F04 owns the average) ---
# Its silent failure is the convention F04 measured: carry a step size across
# the two forms of momentum and the walk takes this many times as long, or
# diverges.  P20 committed the walk that reproduces exactly when rescaled.
CONV_SAME = int(float(committed("p20.tex", "p20.conv.same") or 67))
CONV_FOLD = int(float(committed("p20.tex", "p20.fold") or 10))
emit("p33.conv.same", CONV_SAME)
emit("p33.conv.fold", CONV_FOLD)

# --- precision (P01) ---
# Its silent failure is swamping: under round-to-nearest a contribution below
# half the gap at the running total moves NOTHING, and in bf16 that threshold
# is this fraction of the total.
SWAMP_BF16_PCT = float(committed("p01.tex", "p01.swamp.bf16.pct") or 0.39)
emit("p33.fail.swamp", SWAMP_BF16_PCT, 2)

# --- the schedule and the bound (P17) ---
# LOUD.  Above 2/lambda_max every eigendirection with lambda above the
# threshold grows, and the run does not merely get worse -- it leaves.
LAM_HI = float(committed("p17.tex", "p17.lam.hi") or 20)
LAM_LO = float(committed("p17.tex", "p17.lam.lo") or 1)

# GATE.  P17's committed boundary is 2/lambda_max, and recomputing it here is
# what makes the hand-over real rather than a quotation.  Note what this
# assertion caught on its first run: an earlier draft wrote it as
# `eta_star < 2/lambda_max`, which is the SAME QUANTITY compared with itself
# -- P17's `eta.star` IS the boundary, not the optimum -- and the two print
# identically at two decimals, so nothing but the assertion would have said so.
ETA_BOUND = 2.0 / LAM_HI
_p17_bound = float(committed("p17.tex", "p17.eta.star") or 0.10)
assert abs(ETA_BOUND - _p17_bound) < 5e-3, (ETA_BOUND, _p17_bound)
emit("p33.eta.bound", ETA_BOUND, 2)

# The optimum for plain descent on this bowl is 2/(lambda_hi + lambda_lo), and
# P17 and P20 both committed it.  THE ASSEMBLY'S NUMBER IS THE GAP BETWEEN
# THEM: the step size a schedule wants and the step size that ends the run
# differ by this much, and a schedule spends its whole life inside that band.
# Computed here and GATED against the two programs that committed it, rather
# than read back and reused: reading it back would round it to three decimals
# first, and the margin below is exactly the check that a rounded operand
# breaks.  P05's rule -- a comparison against a value that has already lost
# the digits you are about to test is not a comparison.
ETA_BEST = 2.0 / (LAM_HI + LAM_LO)
for _f, _k in (("p17.tex", "p17.best.eta"), ("p20.tex", "p20.eta.best")):
    _c = committed(_f, _k)
    assert _c is not None and f"{ETA_BEST:.3f}" == _c, (_k, _c, ETA_BEST)
emit("p33.eta.best", ETA_BEST, 3)

# Reported at zero decimals BECAUSE that is the only precision at which the
# exact margin and the margin a reader computes from the two printed figures
# agree -- 4.76 against 5.00 at two.  F05's rule, applied before it bit.
ETA_MARGIN_PCT = reproduces(
    100.0 * (ETA_BOUND - ETA_BEST) / ETA_BOUND, 0,
    (ETA_BOUND, 2), (ETA_BEST, 3),
    op=lambda b, e: 100.0 * (b - e) / b)
emit("p33.eta.margin", ETA_MARGIN_PCT, 0)

# --- clipping and minibatch noise (F06 and P21) ---
# Silent, twice over: accumulation divides by the wrong denominator and the
# gradient is of a different objective, and clipping by value changes the
# direction without saying so.
ACC_RATIO = float(committed("p21.tex", "p21.acc.ratio") or 1.83)
emit("p33.fail.acc", ACC_RATIO, 2)

# The count the assembly is for.
SILENT, LOUD = 4, 2
assert SILENT + LOUD == 6
emit("p33.pieces", SILENT + LOUD)
emit("p33.silent", SILENT)
emit("p33.loud", LOUD)


# ======================================================================
# SECTION 2 --- A LOSS CURVE READ AS EVIDENCE.
#
# F03 defers this here by name.  P21 owns the half about WHEN -- its section 5
# measures the smoother's lag and its trapbox says "read the raw curve when the
# question is *when*, and the smoothed one when the question is *whether*".
# So this program owes the *whether*, and the whole of it is one question asked
# four times: IS THIS SHAPE EVIDENCE, OR IS IT WHAT NOISE DOES?
#
# The noise model is not invented.  A minibatch loss is a mean over B examples
# of a per-example loss whose spread P19 committed while measuring the
# perplexity error, so the observed loss at a step has spread sigma/sqrt(B).
# Nothing is sampled: every answer below is a statement about a normal
# distribution, evaluated with math.erf.
# ======================================================================

SIGMA_TOKEN = 2.0          # P19's per-token loss spread, at its widest row
BATCH = 256                # P21's own top batch size
_p21_b = int(float(committed("p21.tex", "p21.noise.b.hi") or 256))
assert BATCH == _p21_b, (BATCH, _p21_b)
SIGMA_STEP = SIGMA_TOKEN / math.sqrt(BATCH)
emit("p33.sigma.token", SIGMA_TOKEN, 1)
emit("p33.batch", BATCH)
emit("p33.sigma.step", SIGMA_STEP, 3)

# Late in a run the loss moves slowly.  This is the one figure the reader is
# asked to accept as a scenario rather than as a measurement, and it is stated
# on the page as one: a loss falling from 2.5 to 2.4 over ten thousand steps.
DROP, DROP_STEPS = 0.1, 10_000
IMPROVE = DROP / DROP_STEPS
emit("p33.drop", DROP, 1)
emit("p33.drop.steps", DROP_STEPS)
emit("p33.improve", f"{IMPROVE:.0e}")

# --- the plateau ---------------------------------------------------------
# "The loss has not gone below where it was k steps ago."  The true fall over
# those k steps is k * IMPROVE; the two observations differ by a noise term of
# spread SIGMA_STEP * sqrt(2).  So the chance of seeing no improvement is
# exact, and inverting it gives the k at which a flat stretch stops being what
# noise does and starts being evidence.
NOISE_DIFF = SIGMA_STEP * math.sqrt(2.0)
ALPHA = float(committed("p27.tex", "p27.alpha") or 0.05)
Z_ALPHA = z_for(ALPHA)
PLATEAU_K = math.ceil(Z_ALPHA * NOISE_DIFF / IMPROVE)
emit("p33.alpha", ALPHA, 2)
emit("p33.z.alpha", Z_ALPHA, 3)

# Reported to two significant figures, because five do not survive the page.
# A reader multiplying the three printed operands gets 29 080 where the exact
# answer is 29 078: the difference is the rounding in sqrt(2) and in the
# spread, and F05's rule is to report at a precision the page can support.
PLATEAU_ROUND = round(PLATEAU_K, -3)
_from_page = math.ceil(round(Z_ALPHA, 3) * round(SIGMA_STEP, 3)
                       * math.sqrt(2.0) / IMPROVE)
assert round(_from_page, -3) == PLATEAU_ROUND, (_from_page, PLATEAU_K)
assert _from_page != PLATEAU_K, (
    "if these agree exactly the rounding above is not being tested")
emit("p33.plateau.k", PLATEAU_ROUND)

# The claim the frames make is that the answer is very large, so assert THAT
# rather than the figure, which moves with the scenario.
assert PLATEAU_K > 10_000, PLATEAU_K
# And that it really is the crossing point: one step short must still be
# ordinary at the 5 per cent level, and one step past must not.
assert 1.0 - Phi((PLATEAU_K - 1) * IMPROVE / NOISE_DIFF) > ALPHA
assert 1.0 - Phi(PLATEAU_K * IMPROVE / NOISE_DIFF) <= ALPHA

# What a reader actually watches: a few hundred steps of nothing.
WATCH = 500
P_FLAT = 1.0 - Phi(WATCH * IMPROVE / NOISE_DIFF)
emit("p33.watch", WATCH)
emit("p33.p.flat", pct(100.0 * P_FLAT), 1)
assert P_FLAT > 0.4, P_FLAT

# The SAME 500 steps under the other reading of "the loss has not gone below
# where it started", and the two are not close.  P_FLAT above compares TWO
# readings -- now against 500 steps ago -- which is what a person watching a
# dashboard actually does.  Read as a running minimum, the event is that none
# of the 500 readings ever dipped below the first, and that is 500 chances to
# fail rather than one.
#
# It is computed rather than bounded, because the two readings share the
# step-0 noise and a product of marginals would be wrong.  Condition on that
# shared term: given the step-0 noise z (in units of the spread), reading t is
# above the first exactly when its own noise clears z + t*IMPROVE/SIGMA_STEP,
# and those 500 events are then independent.  Simpson over z.
#
# The grid is deliberately coarse and that is checked rather than asserted by
# eye: the integrand is smooth, so 500 panels already agree with 4000 to four
# decimals, and the whole thing costs under a tenth of a second.
def _never_below_first(steps: int, panels: int = 1000,
                       lo: float = -9.0, hi: float = 9.0) -> float:
    d = IMPROVE / SIGMA_STEP
    h = (hi - lo) / panels
    total = 0.0
    for k in range(panels + 1):
        z = lo + k * h
        weight = 1.0 if k in (0, panels) else (4.0 if k % 2 else 2.0)
        logp = 0.0
        for t in range(1, steps + 1):
            q = 1.0 - Phi(z + t * d)
            if q <= 0.0:
                logp = None
                break
            logp += math.log(q)
        if logp is None:
            continue
        density = math.exp(-0.5 * z * z) / math.sqrt(2.0 * math.pi)
        total += weight * density * math.exp(logp)
    return total * h / 3.0

P_FLAT_MIN = _never_below_first(WATCH)
assert abs(P_FLAT_MIN - _never_below_first(WATCH, panels=4000)) < 1e-6, (
    "the Simpson grid is too coarse to report to three decimals")

# Three decimals, not two, and the reason is the recorded rule: divide the two
# numbers AS THE PAGE PRINTS THEM.  At two the page divides to 257 against an
# exact 260; at three it divides to 260.1, which is the same integer.
emit("p33.p.flat.min", pct(100.0 * P_FLAT_MIN), 3)
RATIO = P_FLAT / P_FLAT_MIN
emit("p33.p.flat.ratio", RATIO, 0)
_page = float(VALUES["p33.p.flat"][0]) / float(VALUES["p33.p.flat.min"][0])
assert f"{_page:.0f}" == VALUES["p33.p.flat.ratio"][0], (
    f"the page divides to {_page:.1f} where the ratio prints "
    f"{VALUES['p33.p.flat.ratio'][0]}")
# And the claim the frames make is the ORDER of magnitude rather than the
# figure, so assert that: the running-minimum reading is two orders rarer.
assert RATIO > 100.0, RATIO
assert P_FLAT_MIN < 0.01, P_FLAT_MIN

# --- the spike -----------------------------------------------------------
# A run is long, so the largest deviation in it is large BY CONSTRUCTION.
# This is P27's multiple-comparison arithmetic with steps in place of models,
# and its z is gated against P27's own Bonferroni figure to prove they are one
# calculation rather than two that resemble each other.
STEPS = 100_000
EXPECTED_4SIG = STEPS * (1.0 - Phi(4.0))
SPIKE_Z = z_for(ALPHA / STEPS)
emit("p33.steps", STEPS)
emit("p33.spike.expected", EXPECTED_4SIG, 1)
emit("p33.spike.z", SPIKE_Z, 2)
assert EXPECTED_4SIG > 1.0, EXPECTED_4SIG
assert SPIKE_Z > 4.0, SPIKE_Z

# THE GATE.  P27 corrected a two-sided z for 40 models; the same formula with
# 40 in place of STEPS must return P27's committed figure to the digit.
_p27_models = 40
_z_check = z_for(ALPHA / (2 * _p27_models))
_p27_z = committed("p27.tex", "p27.z.bonf")
assert _p27_z is not None and f"{_z_check:.3f}" == _p27_z, (_z_check, _p27_z)

# --- the suspiciously smooth descent -------------------------------------
# An exponential moving average of independent noise has variance
# (1 - beta)/(1 + beta) times the raw variance -- the sum of a geometric
# series, which is F04's own object.  So the spread a dashboard SHOWS is a
# known fraction of the spread the run HAS, and the fraction is a setting.
BETA = float(committed("p21.tex", "p21.ema.beta") or 0.9)
emit("p33.beta", BETA, 1)


def ema_sd_factor(beta: float) -> float:
    return math.sqrt((1.0 - beta) / (1.0 + beta))


# Checked against the series itself rather than against the closed form twice:
# sum of ((1-b) b^k)^2 over k is the variance, and it must equal the formula.
_series = sum(((1.0 - BETA) * BETA ** k) ** 2 for k in range(20_000))
assert abs(_series - ema_sd_factor(BETA) ** 2) < 1e-12, _series

SMOOTH_FACTOR = ema_sd_factor(BETA)
emit("p33.smooth.pct", pct(100.0 * SMOOTH_FACTOR), 1)

BETA_DASH = 0.98                       # what a dashboard is usually left at
emit("p33.beta.dash", BETA_DASH, 2)
emit("p33.smooth.dash", ema_sd_factor(BETA_DASH), 3)
emit("p33.smooth.dash.times",
     reproduces(1.0 / ema_sd_factor(BETA_DASH), 1,
                (ema_sd_factor(BETA_DASH), 3), op=lambda f: 1.0 / f), 1)
assert ema_sd_factor(BETA_DASH) < ema_sd_factor(BETA)

# --- and the one shape that IS diagnostic --------------------------------
# Divergence.  P17 says exactly when, so it is the only one of the four that
# needs no statistics at all: above the boundary the walk leaves, and the
# factor per step is bigger than one in the steepest direction.
ETA_OVER = 0.11                        # P17's own demonstration step size
_p17_demo = float(committed("p17.tex", "p17.demo.eta") or 0.11)
assert abs(ETA_OVER - _p17_demo) < 1e-9
DIVERGE_FACTOR = abs(1.0 - ETA_OVER * LAM_HI)
emit("p33.eta.over", ETA_OVER, 2)
emit("p33.diverge.factor", DIVERGE_FACTOR, 1)
assert DIVERGE_FACTOR > 1.0, DIVERGE_FACTOR


# ======================================================================
# SECTION 3 --- EXPERIMENT E10: A SCALING-LAW FIT, AND ITS EXTRAPOLATION.
#
# F03 hands this over by name and owns the machinery: a power law is a
# straight line on log-log axes and the gradient of the line is the exponent.
# What it does not do is FIT one, and the brief asks for the fit with its
# extrapolation error stated rather than for a law of nature.
#
# The curriculum notes specify E10 on "published numbers".  P32's split asked
# of it: does the claim need external data, or is it a statement about the
# fit?  THE HALF THAT CARRIES THE ARGUMENT NEEDS NOTHING EXTERNAL -- how far a
# power-law fit can be trusted past its last point is a property of the fit and
# of the span, and it is exactly computable when the truth is known because
# this script chose it.  What a paper would add is one specific exponent, and
# the frames say so rather than pretending the general claim needs it.
#
# The truth here is the form the scaling-law literature itself uses: an
# irreducible loss plus a power law.  A pure power law is fitted to it, which
# is what everybody fits, and the mismatch is the whole finding.
# ======================================================================


def least_squares_line(xs, ys):
    """Slope and intercept of the least-squares line.  Two sums and a divide."""
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    slope = sxy / sxx
    return slope, my - slope * mx


# GATE, of P09's third kind: two programs must not be able to disagree about
# what a least-squares line IS.  P08 fitted three points by hand and committed
# the answer; this routine has to return it.
_p8x, _p8y = [1.0, 2.0, 3.0], [1.0, 3.0, 2.0]
_s, _i = least_squares_line(_p8x, _p8y)
assert f"{_s:.1f}" == committed("p08.tex", "p08.ls.slope"), _s
assert f"{_i:.0f}" == committed("p08.tex", "p08.ls.intercept"), _i
_sse = sum((y - (_s * x + _i)) ** 2 for x, y in zip(_p8x, _p8y))
assert f"{_sse:.1f}" == committed("p08.tex", "p08.ls.sse"), _sse

# --- the truth, chosen and stated as a choice --------------------------
L_INF = 1.70          # the irreducible loss: what no amount of data removes
AMP = 3.71            # the reducible part's amplitude
ALPHA_TRUE = 0.076    # and its exponent
emit("p33.fit.linf", L_INF, 2)
emit("p33.fit.alpha", ALPHA_TRUE, 3)


def truth(n: float) -> float:
    return L_INF + AMP * n ** (-ALPHA_TRUE)


# --- the measured span: three decades, seven points --------------------
LO_DEC, HI_DEC, POINTS = 6, 9, 7
DECADES = HI_DEC - LO_DEC
NS = [10.0 ** (LO_DEC + DECADES * i / (POINTS - 1)) for i in range(POINTS)]
LS = [truth(n) for n in NS]
emit("p33.fit.lo", f"1e{LO_DEC}")
emit("p33.fit.hi", f"1e{HI_DEC}")
emit("p33.fit.decades", DECADES)
emit("p33.fit.loss.lo", LS[0], 2)
emit("p33.fit.loss.hi", LS[-1], 2)

# --- the fit: a PURE power law, which is what gets fitted ---------------
SLOPE, INTERCEPT = least_squares_line([math.log(n) for n in NS],
                                      [math.log(l) for l in LS])
B_FIT = -SLOPE
emit("p33.fit.b", B_FIT, 4)


def fitted(n: float) -> float:
    return math.exp(INTERCEPT) * n ** SLOPE


# It looks straight.  That is the point, so it is measured rather than
# asserted: the largest relative miss anywhere in the fitted span.
RESID = max(abs(fitted(n) - truth(n)) / truth(n) for n in NS)
emit("p33.fit.resid", pct(100.0 * RESID), 2)
assert RESID < 0.01, RESID          # under one per cent: indistinguishable
                                    # from plotting accuracy on log-log axes

# --- and it is wrong outside the span ----------------------------------
OUT_DEC = 12
N_OUT = 10.0 ** OUT_DEC
emit("p33.out.dec", OUT_DEC)
emit("p33.out.truth", truth(N_OUT), 3)
emit("p33.out.fitted", fitted(N_OUT), 3)
OUT_ERR = pct(100.0 * (truth(N_OUT) - fitted(N_OUT)) / truth(N_OUT))
emit("p33.out.err", OUT_ERR, 1)

# THE INVARIANT, and the first draft got it wrong in the way this book has
# recorded four times: it asserted `OUT_ERR > 20 * RESID`, which is a
# THRESHOLD CHOSEN SO A CLAIM WOULD PASS.  It failed at 13.6 against 20, and
# the failure is the better statement -- what is true has no constant in it.
# The error outside the span GROWS WITH DISTANCE, monotonically, and is
# unbounded, while the error inside is bounded by the residual.
_errs = [abs(truth(10.0 ** d) - fitted(10.0 ** d)) / truth(10.0 ** d)
         for d in range(HI_DEC, HI_DEC + 12)]
assert all(b > a for a, b in zip(_errs, _errs[1:])), _errs
assert _errs[0] < RESID * 2 and _errs[-1] > 10 * _errs[0], (_errs[0], _errs[-1])

# The unbounded half, exactly.  A pure power law goes to zero; the truth does
# not.  So there is a size at which the fit predicts a loss BELOW the floor,
# and it can be solved for rather than searched.
N_ABSURD = math.exp((INTERCEPT - math.log(L_INF)) / (-SLOPE))
ABSURD_DEC = math.log10(N_ABSURD)
emit("p33.absurd.dec", ABSURD_DEC, 1)
emit("p33.absurd.past", ABSURD_DEC - HI_DEC, 1)
assert fitted(N_ABSURD) < truth(N_ABSURD)
assert abs(fitted(N_ABSURD) - L_INF) < 1e-9, fitted(N_ABSURD)

# --- what the fit's OWN reported uncertainty says ----------------------
# The standard error of a least-squares slope is built from the residuals, so
# a fit to data that lies on a smooth curve reports near-zero uncertainty --
# about the noise, and about nothing else.  That is the sentence the section
# exists for, and it is arithmetic rather than opinion.
_lx = [math.log(n) for n in NS]
_ly = [math.log(l) for l in LS]
_res = [y - (SLOPE * x + INTERCEPT) for x, y in zip(_lx, _ly)]
_s2 = sum(r * r for r in _res) / (POINTS - 2)
_mx = sum(_lx) / POINTS
SE_B = math.sqrt(_s2 / sum((x - _mx) ** 2 for x in _lx))
emit("p33.fit.se", f"{SE_B:.0e}")
# Three decades out, the interval that uncertainty gives:
# And the claim is not that the band is small.  It is that THE TRUTH LIES
# OUTSIDE IT: two standard errors on the exponent, carried three decades, do
# not reach the value the fit is missing.  That is checkable without a
# threshold, and it is what "an empirical fit with a stated extrapolation
# error" turns out to be worth.
_hi = math.exp(INTERCEPT) * N_OUT ** (SLOPE + 2 * SE_B)
_lo = math.exp(INTERCEPT) * N_OUT ** (SLOPE - 2 * SE_B)
assert not (_lo <= truth(N_OUT) <= _hi), (_lo, truth(N_OUT), _hi)
emit("p33.fit.band.lo", _lo, 3)
emit("p33.fit.band.hi", _hi, 3)


# --- the accumulation a further problem asks about ------------------------
ACC_TOKENS = (1000, 10, 500, 490)
ACC_LOSSES = (2, 8, 3, 3)
_pooled = (sum(Fraction(t * l) for t, l in zip(ACC_TOKENS, ACC_LOSSES))
           / Fraction(sum(ACC_TOKENS)))
_naive = sum(Fraction(l) for l in ACC_LOSSES) / Fraction(len(ACC_LOSSES))
emit("p33.accum.pooled", float(_pooled), 3)
emit("p33.accum.naive", float(_naive), 0)
# The exercise turns on the two denominators differing, so assert THAT rather
# than either figure: the naive average is dragged up by the ten-token batch,
# which carries one two-hundredth of the tokens and a quarter of the weight.
assert _naive > _pooled, (_naive, _pooled)
assert float(_naive) / float(_pooled) > 1.5, float(_naive) / float(_pooled)
assert sum(ACC_TOKENS) == 2000


# ======================================================================
# THE TRANSCRIPT.  The program's least believable claim is section 2's, so
# that is the one the reader gets to run: a healthy descent looks flat for
# five hundred steps about half the time.  Both figures come out of one
# expression, and the rounding is INSIDE the listing (P19's rule) so the
# printed line and the printed result cannot come apart.
# ======================================================================
NOTES: list[str] = []
_t = [
    ">>> from math import erf, sqrt",
    ">>> def phi(z): return 0.5 * (1 + erf(z / sqrt(2)))",
    "...",
    ">>> sigma = 2 / sqrt(256)   # a batch mean of a spread-2 loss",
    ">>> improve = 1e-5          # the true fall, per step",
    ">>> gap = sigma * sqrt(2)",
    ">>> round(1 - phi(500 * improve / gap), 3)",
]
_p500 = round(1.0 - Phi(500 * IMPROVE / NOISE_DIFF), 3)
_t.append(repr(_p500))
_t.append(">>> round(1 - phi(29000 * improve / gap), 3)")
_pk = round(1.0 - Phi(29000 * IMPROVE / NOISE_DIFF), 3)
_t.append(repr(_pk))

# The listing's own claims, asserted rather than trusted.
assert abs(_p500 - 0.489) < 1e-9, _p500
assert _pk <= ALPHA + 1e-9, _pk
assert f"{100.0 * _p500:.1f}" == VALUES["p33.p.flat"][0]
assert max(len(x) for x in _t) <= 64, max(_t, key=len)
TRANSCRIPT.mkdir(parents=True, exist_ok=True)
(TRANSCRIPT / "p33-how-flat.txt").write_text("\n".join(_t) + "\n",
                                             encoding="utf8")

NOTES.append(
    f"  * of the six pieces, {SILENT} fail silently and {LOUD} loudly, and the"
    f" {SILENT} silent ones are the ones that reach the curve")
NOTES.append(
    f"  * a flat stretch must last about {PLATEAU_ROUND:,} steps before it is"
    f" evidence; at 500 steps a healthy run looks flat {100 * _p500:.1f}% of"
    " the time")
NOTES.append(
    f"  * a spike must exceed {SPIKE_Z:.2f} sigma in a {STEPS:,}-step run,"
    f" where {EXPECTED_4SIG:.1f} four-sigma steps are expected")
NOTES.append(
    f"  * the fit is straight to {100 * RESID:.2f}% over {DECADES} decades and"
    f" predicts a loss BELOW the floor at 10^{ABSURD_DEC:.1f}"
    f" -- {ABSURD_DEC - HI_DEC:.1f} decades past the last measured point")


# ======================================================================
OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open("w", encoding="utf8") as fh:
    fh.write("% Generated by code/p33_training_run.py -- do not edit.\n")
    for k, (body, numeric) in VALUES.items():
        fh.write(f"\\{'mfaval' if numeric else 'mfavaltext'}{{{k}}}{{{body}}}\n")

print(f"P33: {len(VALUES)} values -> {OUT}")
for n in NOTES:
    print(n)
