graph LR
  A["what a plug-in estimate<br/>reports on a sample"] --> B["part of it is the relationship<br/>you are asking about"]
  B --> C["and part is the cells<br/>divided by the items,<br/>which is there either way"]
