#!/usr/bin/env python3
"""Regenerate the program stubs and structure.tex from tools/programs.json.

The manifest is the single source of the part and program sequence, so a change
to the curriculum -- inserting a program, renumbering a part, rewriting a brief
-- is one edit here and one run of this script, rather than forty-seven edits
made by hand and a renumbering done by eye.

It will NEVER overwrite a program that has been written. A file that no longer
carries a \\programstub{} is finished prose and is left exactly alone; if such a
program has been renumbered, the script says so and stops, because moving
written work is a decision and not a side effect.

Run:  python3 tools/gen_stubs.py            (from the repository root)
      python3 tools/gen_stubs.py --check    (fail if anything is out of date)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

EN_STUB = """%% {key} --- {en}
%%
%% Stub, generated by tools/gen_stubs.py from tools/programs.json.
%% The brief below is the contract for this program: what it must argue, and
%% what it must buy the reader. Writing the program means deleting the
%% \\programstub{{}} block and replacing it with the program -- after which this
%% file is never regenerated. If the brief turns out to be wrong once the
%% mathematics has been worked, change it in the manifest and record the
%% contradiction in CLAUDE.md under *Resolved questions*.

\\program{{{en}}}
\\label{{prog:{key}}}

\\programstub{{%
{brief}

\\medskip
\\textbf{{Planned length:}} {frames} frames.
}}
"""

PL_STUB = """%% {key} --- {pl}
%%
%% Zalążek, wygenerowany przez tools/gen_stubs.py z tools/programs.json.
%% Poniższy opis jest kontraktem tego programu: co ma uzasadnić i co ma dać
%% czytelnikowi. Napisanie programu oznacza usunięcie bloku \\programstub{{}} i
%% zastąpienie go programem -- po czym ten plik nie jest już generowany.

\\program{{{pl}}}
\\label{{prog:{key}}}

\\programstub{{%
\\textit{{[Opis do przetłumaczenia --- patrz wydanie angielskie.]}}

{brief}

\\medskip
\\textbf{{Planowana długość:}} {frames} ramek.
}}
"""

STRUCTURE_HEAD = r"""% ============================================================
%  structure.tex --- the part and program sequence
%
%  GENERATED by tools/gen_stubs.py from tools/programs.json. Edit the manifest,
%  not this file.
%
%  Shared by both editions. There is exactly one list of programs in this
%  repository, and both main files read it, so the Polish and English editions
%  cannot contain different programs. A program added here appears in both, or
%  fails the build in whichever language has not been written.
% ============================================================

\newcommand{\includeprogram}[1]{\include{programs/\booklang/#1}}
"""


def latexify(s: str) -> str:
    """Turn a brief written as prose into LaTeX that compiles.

    `x` becomes \\code{x}, and anything inside it that is really mathematics --
    an exponent, a subscript -- becomes maths, because \\code{n^2} is a missing
    dollar and \\code{n\\textasciicircum{}2} is unreadable. This ran as a
    one-off patch once and the next regeneration undid it, which is why it
    lives here.
    """
    s = s.replace("\\", "\\textbackslash{}") if "\\code" not in s and "\\text" not in s else s
    s = re.sub(r"`([^`]*)`", lambda m: r"\code{" + m.group(1) + "}", s)
    # \code{} bodies that are actually maths
    def fix(m: re.Match) -> str:
        body = m.group(1)
        if re.search(r"[\^_]", body):
            body = re.sub(r"\^(\w+)", r"^{\1}", body)
            return "$" + body + "$"
        return r"\code{" + body.replace("_", r"\_") + "}"
    s = re.sub(r"\\code\{([^{}]*)\}", fix, s)
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        s = s.replace(a, b)
    s = re.sub(r'"([^"]{1,200}?)"', lambda m: r"\enquote{" + " ".join(m.group(1).split()) + "}", s, flags=re.S)
    s = re.sub(r"(?<!-)--- ", r"\\dash{} ", s)
    return s


def wrap(s: str, width: int = 76) -> str:
    return "\n\n".join(textwrap.fill(p, width) for p in s.split("\n\n"))


def written(path: Path) -> bool:
    return path.is_file() and "\\programstub{" not in path.read_text(encoding="utf8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report what would change and exit non-zero, writing nothing")
    a = ap.parse_args()

    m = json.loads((ROOT / "tools" / "programs.json").read_text(encoding="utf8"))
    progs, parts = m["programs"], m["parts"]
    byid = {p["id"]: p for p in progs}
    wanted = {p["file"] + ".tex" for p in progs}

    changed: list[str] = []

    # A written program whose file name is no longer in the manifest has been
    # renumbered under it. That is a decision, not a side effect.
    for lang in ("en", "pl"):
        for f in sorted((ROOT / "programs" / lang).glob("*.tex")):
            if f.name not in wanted and written(f):
                print(f"  REFUSING: {f} is written and the manifest no longer "
                      f"lists it. Rename it deliberately, then re-run.")
                return 2

    for lang in ("en", "pl"):
        for f in sorted((ROOT / "programs" / lang).glob("*.tex")):
            if f.name not in wanted:
                changed.append(f"delete {f.relative_to(ROOT)}")
                if not a.check:
                    f.unlink()

    for p in progs:
        brief = wrap(latexify(p["brief"]))
        for lang, tmpl in (("en", EN_STUB), ("pl", PL_STUB)):
            path = ROOT / "programs" / lang / (p["file"] + ".tex")
            if written(path):
                continue
            body = tmpl.format(key=p["key"], en=p.get("en", ""), pl=p.get("pl", ""),
                               brief=brief, frames=p["frames"])
            if not path.is_file() or path.read_text(encoding="utf8") != body:
                changed.append(f"write {path.relative_to(ROOT)}")
                if not a.check:
                    path.write_text(body, encoding="utf8")

    out = [STRUCTURE_HEAD]
    for i, part in enumerate(parts):
        out.append("\n\\part{\\lblPart%s}\n" % ROMAN[i])
        if i == 0:
            out.append("\\foundationnumbering\n")
        elif i == 1:
            out.append("\\mainnumbering\n")
        for pid in part["ids"]:
            out.append("\\includeprogram{%s}\n" % byid[pid]["file"])
    text = "".join(out)
    sp = ROOT / "structure.tex"
    if not sp.is_file() or sp.read_text(encoding="utf8") != text:
        changed.append("write structure.tex")
        if not a.check:
            sp.write_text(text, encoding="utf8")

    if a.check:
        for c in changed:
            print(f"  OUT OF DATE: {c}")
        if not changed:
            print(f"  {len(progs)} programs, {sum(p['frames'] for p in progs)} planned "
                  f"frames; stubs and structure.tex are current.")
        return 1 if changed else 0

    print(f"  {len(progs)} programs, {sum(p['frames'] for p in progs)} planned frames; "
          f"{len(changed)} file(s) written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
