#!/usr/bin/env python3
r"""Regenerate the per-volume KDP wiring from tools/volumes.json + programs.json.

The split is a VIEW over the manifest, never a fork of it: this script reads the
part and program sequence out of tools/programs.json and the volume boundaries
out of tools/volumes.json, and writes every per-volume file under kdp/generated.
Edit the two manifests, not the output.

WHAT IT GENERATES, and why each exists:

  structure-vN.tex   the volume's parts, in manifest order, with the NUMBERING
                     OFFSET.  \mainnumbering sets the chapter counter to 0, so a
                     volume that starts at Part IV would call P12 "Program 1" --
                     silently, and every Summary bracket, Quiz route and
                     cross-reference in the series would then be wrong.  The
                     offset is the whole reason this file is generated rather
                     than assembled by hand.

  volmap-vN.tex      one \mfavolref per program NOT in this volume.  See
                     kdp/preamble-kdp.tex for why supplying the label beats
                     intercepting \ref.

  seriesmap-vN.tex   the page listing every volume and what it contains, so it
                     cannot drift from the actual split.

  body-vN.tex        the volume's document body, on body.tex's own shape.

  vN-LANG.tex        the four-line main file, on main-en.tex's shape.

Run:  python3 tools/gen_volumes.py            (from the repository root)
      python3 tools/gen_volumes.py --check    (fail if anything is out of date)
      python3 tools/gen_volumes.py --report   (print the split and its arithmetic)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kdp" / "generated"
ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX"]
LANGS = ("en", "pl")

# Volume numerals are roman too, and deliberately a different sequence from the
# part numerals: a reader holding "Volume III" must not have to work out that it
# contains Parts IV to VI.
VOL_ROMAN = {1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI"}

BANNER = ("%% GENERATED by tools/gen_volumes.py from tools/volumes.json and\n"
          "%% tools/programs.json. Edit the manifests, not this file.\n")


# ---------------------------------------------------------------- loading ----
def load():
    progs = json.loads((ROOT / "tools" / "programs.json").read_text("utf8"))
    vols = json.loads((ROOT / "tools" / "volumes.json").read_text("utf8"))
    part_ids = {ROMAN[i]: p["ids"] for i, p in enumerate(progs["parts"])}
    by_id = {p["id"]: p for p in progs["programs"]}
    return progs, vols, part_ids, by_id


def printed_number(pid: str) -> str:
    """The number the reader sees: F1..F13 keep their letter, P12 prints as 12."""
    return pid if pid.startswith("F") else pid[1:]


def volume_of(vols, part_ids):
    """program id -> volume number, and part numeral -> volume number."""
    part_vol, prog_vol = {}, {}
    for v in vols["volumes"]:
        for part in v["parts"]:
            part_vol[part] = v["n"]
            for pid in part_ids[part]:
                prog_vol[pid] = v["n"]
    return part_vol, prog_vol


# ------------------------------------------------------------- validation ----
def validate(progs, vols, part_ids) -> list[str]:
    """Every rule SS4.2 states, checked against the manifest rather than assumed."""
    errs = []
    declared = [p for v in vols["volumes"] for p in v["parts"]]

    for part in declared:
        if part not in part_ids:
            errs.append(f"volumes.json names part {part}, which programs.json "
                        f"does not have (it has {', '.join(part_ids)})")
    missing = [p for p in ROMAN if p not in declared]
    if missing:
        errs.append(f"part(s) {', '.join(missing)} are in no volume; every part "
                    f"must appear in exactly one")
    dupes = sorted({p for p in declared if declared.count(p) > 1})
    if dupes:
        errs.append(f"part(s) {', '.join(dupes)} appear in more than one volume")

    # Order must follow the manifest, so cross-references point backwards where
    # they can. Checked positionally rather than by sorting: a volume whose parts
    # are out of manifest order is the defect, not a presentation choice.
    if declared != sorted(declared, key=lambda p: ROMAN.index(p) if p in ROMAN else 99):
        errs.append(f"volume order does not follow programs.json: {declared}")

    for v in vols["volumes"]:
        idx = [ROMAN.index(p) for p in v["parts"] if p in ROMAN]
        if idx and idx != list(range(idx[0], idx[0] + len(idx))):
            errs.append(f"volume {v['n']} is not a contiguous run of parts: "
                        f"{v['parts']}")
        for lang in LANGS:
            if not (v.get("title") or {}).get(lang):
                errs.append(f"volume {v['n']} has no {lang} title")

    ns = [v["n"] for v in vols["volumes"]]
    if ns != list(range(1, len(ns) + 1)):
        errs.append(f"volume numbers must run 1..N in order; got {ns}")
    for v in vols["volumes"]:
        if v["n"] not in VOL_ROMAN:
            errs.append(f"volume {v['n']} has no roman numeral; extend VOL_ROMAN")
    return errs


# --------------------------------------------------------------- emitters ----
def gen_structure(v, part_ids) -> str:
    out = [BANNER,
           "%% The numbering offset below is load-bearing. \\mainnumbering sets the",
           "%% chapter counter to 0, so without it the first main program in this",
           "%% volume would print as \"Program 1\" whatever its number in the series.",
           "",
           "\\newcommand{\\includeprogram}[1]{\\include{programs/\\booklang/#1}}",
           ""]
    seen_main = False
    for part in v["parts"]:
        ids = part_ids[part]
        out.append(f"\\part{{\\lblPart{part}}}")
        if ids[0].startswith("F"):
            out.append("\\foundationnumbering")
        elif not seen_main:
            out.append("\\mainnumbering")
            first = int(ids[0][1:])
            if first > 1:
                out.append(f"\\setcounter{{chapter}}{{{first - 1}}}"
                           f"  % so {ids[0]} prints as Program {first}")
            seen_main = True
        for pid in ids:
            out.append(f"\\includeprogram{{{part_ids['__file__'][pid]}}}")
        out.append("")
    return "\n".join(out)


def gen_volmap(v, vols, by_id, prog_vol) -> str:
    out = [BANNER,
           "%% Every program NOT in this volume, and the appendices this volume",
           "%% does not carry. Each line DEFINES the label \\ref is looking for, so",
           "%% \\ref resolves normally and cannot raise an unresolved reference.",
           ""]
    last = max(x["n"] for x in vols["volumes"])
    for pid, p in by_id.items():
        tv = prog_vol[pid]
        if tv != v["n"]:
            out.append(f"\\mfavolref{{prog:{p['key']}}}{{{printed_number(pid)}}}"
                       f"{{{VOL_ROMAN[tv]}}}")
    if v["n"] != last:
        out += ["",
                "%% Appendices E and F are in the final volume only, and the front",
                "%% matter references both -- three unresolved references in every",
                "%% other volume without these.",
                f"\\mfavolref{{app:E}}{{E}}{{{VOL_ROMAN[last]}}}",
                f"\\mfavolref{{app:F}}{{F}}{{{VOL_ROMAN[last]}}}",
                f"\\mfavolref{{sec:E-sources}}{{E.1}}{{{VOL_ROMAN[last]}}}"]
    return "\n".join(out) + "\n"


def gen_seriesmap(v, vols, part_ids) -> str:
    """The series map, generated so it cannot drift from the actual split."""
    out = [BANNER,
           "%% Printed in every volume. Generated from tools/volumes.json, so it",
           "%% cannot disagree with the split it describes.",
           "",
           "\\mfaseriesmap{%"]
    rows = []
    for w in vols["volumes"]:
        progs = [pid for part in w["parts"] for pid in part_ids[part]]
        span = (f"{printed_number(progs[0])}--{printed_number(progs[-1])}"
                if progs else "")
        parts = ", ".join(w["parts"])
        here = "\\mfahere" if w["n"] == v["n"] else ""
        rows.append(f"  \\mfaseriesrow{{{VOL_ROMAN[w['n']]}}}"
                    f"{{\\mfavoltitleof{{{w['n']}}}}}{{{parts}}}"
                    f"{{{span}}}{{{here}}}")
    out.append(" \\\\\n".join(rows))
    out.append("}")
    return "\n".join(out) + "\n"


def gen_body(v, vols) -> str:
    last = max(x["n"] for x in vols["volumes"])
    tail = ""
    if v["n"] == last:
        tail = ("\\include{appendices/\\booklang/appE-further-reading}\n"
                "\\include{appendices/\\booklang/appF-manifest}\n")
    return f"""{BANNER}%% This volume's document body, on body.tex's own shape.
%%
%% Appendices A and C and the index are ACCUMULATED as the programs are
%% typeset, so they scope themselves to this volume with nothing to configure --
%% measured: Appendix C is 18 pages here against 70 for the whole book.
%% B and D are reference matter and are carried whole in every volume.
%% E and F are the series' own back matter and are in the final volume only.

\\begin{{document}}

\\frontmatter
\\input{{kdp/frontmatter/\\booklang/volume-title}}
\\input{{kdp/frontmatter/\\booklang/volume-copyright}}
\\input{{kdp/generated/seriesmap-v{v['n']}}}
\\tableofcontents
\\input{{frontmatter/\\booklang/how-to-use}}
%% The whole-book introduction is carried in every volume deliberately: it is
%% the series' own map, a Volume III reader needs it, and check_structure.py
%% --parts reads exactly this file, so keeping it leaves that gate green with
%% no volume mode to write.
\\input{{frontmatter/\\booklang/introduction}}

\\mainmatter
\\input{{kdp/generated/structure-v{v['n']}}}

\\appendix
\\part{{\\lblPartAppendices}}
\\include{{appendices/\\booklang/appA-answers}}
\\include{{appendices/\\booklang/appB-notation}}
\\include{{appendices/\\booklang/appC-formulae}}
\\include{{appendices/\\booklang/appD-terminology}}
{tail}
\\backmatter
\\printindex

%% An odd page count prints the last leaf as a stray recto. See
%% \\mfapadverso in kdp/preamble-kdp.tex.
\\clearpage
\\mfapadverso

\\end{{document}}
"""


def gen_volinfo(v, vols, lang) -> str:
    """This volume's own identity, for the per-volume title and copyright pages.

    Everything here comes from tools/volumes.json. An ISBN that has not been
    assigned yet is \relax rather than an empty string, so the copyright page
    can tell "no ISBN" from "an ISBN that is the empty string" and print
    neither a stray label nor a wrong number.
    """
    isbn = (v.get("isbn") or {}).get(lang)
    rows = [BANNER,
            f"\\def\\mfaseriestitle{{{vols['series'][lang]}}}",
            f"\\def\\mfavolnumeral{{{VOL_ROMAN[v['n']]}}}",
            f"\\def\\mfavoltitlehere{{{v['title'][lang]}}}",
            f"\\def\\mfavolsubtitle{{{(v.get('subtitle') or {}).get(lang) or ''}}}",
            f"\\def\\mfabookauthor{{{vols['author']}}}"]
    rows.append(f"\\def\\mfavolisbn{{{isbn}}}" if isbn
                else "\\let\\mfavolisbn\\relax")
    return "\n".join(rows) + "\n"


def gen_main(v, vols, lang) -> str:
    pt = vols["body_pt"]
    title = v["title"][lang]
    series = vols["series"][lang]
    return f"""%% {BANNER[3:].strip()}
%%
%%  {series}
%%  Volume {VOL_ROMAN[v['n']]} -- {title}
%%
%%  KDP paperback interior: {vols['trim']['name']} in at {pt}pt, black ink on
%%  white paper. Differs from the trade and A4 editions in the preamble it
%%  reads and in nothing else; the programs are the same files.
%%
%%  Build:  make kdp-v{v['n']}      (both languages)
%%          make kdp            (every volume)

\\documentclass[{pt}pt,twoside,openright]{{book}}

\\def\\booklang{{{lang}}}
\\def\\bookpaper{{standard}}
\\def\\mfavolume{{{v['n']}}}
\\input{{kdp/generated/volinfo-v{v['n']}-{lang}}}
\\input{{kdp/generated/voltitles-{lang}}}
\\input{{kdp/preamble-kdp}}
\\input{{kdp/generated/volmap-v{v['n']}}}

\\hypersetup{{pdftitle={{{series} -- {title}}}}}

\\input{{kdp/generated/body-v{v['n']}}}
"""


# ------------------------------------------------------------------- main ----
def build_all():
    progs, vols, part_ids, by_id = load()
    errs = validate(progs, vols, part_ids)
    if errs:
        return None, errs
    part_ids = dict(part_ids)
    part_ids["__file__"] = {p["id"]: p["file"] for p in progs["programs"]}
    _, prog_vol = volume_of(vols, part_ids)

    files: dict[str, str] = {}
    for v in vols["volumes"]:
        n = v["n"]
        files[f"structure-v{n}.tex"] = gen_structure(v, part_ids)
        files[f"volmap-v{n}.tex"] = gen_volmap(v, vols, by_id, prog_vol)
        files[f"seriesmap-v{n}.tex"] = gen_seriesmap(v, vols, part_ids)
        files[f"body-v{n}.tex"] = gen_body(v, vols)
        for lang in LANGS:
            files[f"volinfo-v{n}-{lang}.tex"] = gen_volinfo(v, vols, lang)
            files[f"v{n}-{lang}.tex"] = gen_main(v, vols, lang)
    # The volume titles, as macros, so the series map is localised without the
    # generator having to know which edition it is writing for.
    for lang in LANGS:
        rows = [BANNER]
        for v in vols["volumes"]:
            rows.append(f"\\expandafter\\def\\csname mfavoltitle{v['n']}\\endcsname"
                        f"{{{v['title'][lang]}}}")
        files[f"voltitles-{lang}.tex"] = "\n".join(rows) + "\n"
    return files, []


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if anything on disk is out of date")
    ap.add_argument("--report", action="store_true",
                    help="print the split and its arithmetic")
    a = ap.parse_args()

    files, errs = build_all()
    if errs:
        for e in errs:
            print(f"  volumes.json: {e}")
        return 1

    if a.report:
        _, vols, part_ids, _ = load()
        print(f"  {len(vols['volumes'])} volumes, {vols['body_pt']}pt, "
              f"{vols['trim']['name']} in")
        for v in vols["volumes"]:
            progs = [pid for part in v["parts"] for pid in part_ids[part]]
            print(f"    Volume {VOL_ROMAN[v['n']]}: Parts {', '.join(v['parts'])}"
                  f"  ({len(progs)} programs: {progs[0]}..{progs[-1]})"
                  f"  {v['title']['en']}")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, text in files.items():
        p = OUT / name
        if not p.exists() or p.read_text("utf8") != text:
            stale.append(name)
            if not a.check:
                p.write_text(text, "utf8")
    # A file left behind by a split that has since changed is as wrong as a
    # stale one, so the directory is compared rather than only written to.
    extra = sorted(p.name for p in OUT.glob("*.tex") if p.name not in files)
    for name in extra:
        if not a.check:
            (OUT / name).unlink()

    if a.check:
        if stale or extra:
            for n in stale:
                print(f"  kdp/generated/{n} is out of date")
            for n in extra:
                print(f"  kdp/generated/{n} belongs to no volume")
            print("  Run: python3 tools/gen_volumes.py")
            return 1
        print(f"  {len(files)} generated volume files are current "
              f"({len(json.loads((ROOT / 'tools' / 'volumes.json').read_text('utf8'))['volumes'])} volumes).")
        return 0

    print(f"  wrote {len(stale)} of {len(files)} files to kdp/generated"
          + (f", removed {len(extra)}" if extra else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
