#!/usr/bin/env python3
r"""Cover specification and a correctly-dimensioned template, per volume.

This does NOT design a cover. It computes the one thing a designer cannot
guess -- the spine width, which is a function of the page count and therefore
of the finished interior -- and draws a template at exactly the right size with
non-printing guides, so that whatever is designed is designed in the right box.

    spine_in  = pages x thickness_per_page        (white paper: 0.002252 in)
    height_in = 9.00 + 2 x 0.125                  (bleed top and bottom)
    width_in  = 2 x 6.00 + spine_in + 2 x 0.125   (bleed left and right)

The page count is read from the BUILT interior rather than from any manifest,
because a spine width copied from a plan is a spine width that will be wrong
the first time a paragraph changes.

Run:  python3 tools/kdpcover.py --all
      python3 tools/kdpcover.py build/kdp/tex/kdp-v3-en.pdf
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STAGE = ROOT / "build" / "kdp" / "tex"
OUT = ROOT / "build" / "kdp"

BLEED_IN = 0.125
SAFE_IN = 0.25
# KDP will not print text on the spine of a book under this many pages: the
# spine is too narrow to register reliably.
SPINE_TEXT_MIN_PAGES = 79


def pages_of(pdf: Path) -> int:
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    return int(out.split("Pages:")[1].split()[0])


def spec(pages: int, cfg: dict, vol: dict, lang: str, pdf: Path) -> dict:
    t = cfg["paper"]["thickness_in_per_page"]
    trim_w = cfg["trim"]["width_mm"] / 25.4
    trim_h = cfg["trim"]["height_mm"] / 25.4
    spine = pages * t
    return {
        "volume": vol["n"], "language": lang, "interior": pdf.name,
        "page_count": pages,
        "trim_width_in": round(trim_w, 4), "trim_height_in": round(trim_h, 4),
        "spine_width_in": round(spine, 4),
        "cover_width_in": round(2 * trim_w + spine + 2 * BLEED_IN, 4),
        "cover_height_in": round(trim_h + 2 * BLEED_IN, 4),
        "bleed_in": BLEED_IN, "safe_zone_in": SAFE_IN,
        "paper": cfg["paper"]["stock"], "ink": "black_and_white",
        "spine_text_allowed": pages >= SPINE_TEXT_MIN_PAGES,
        "spine_text_min_pages": SPINE_TEXT_MIN_PAGES,
        "title": vol["title"][lang],
        "_note": ("Spine width is derived from this interior's own page count. "
                  "Rebuild the cover whenever the interior page count changes."),
    }


def template_tex(s: dict) -> str:
    """A page that IS the cover size, with the guides drawn on it absolutely.

    NOT standalone[tightpage]: that sizes the page to the INK, so the 0.4 pt
    guide rule made the template 0.0055 in larger than the spec it prints --
    a designer would then build to a box 0.4 pt wider than the one KDP wants.
    geometry fixes the page and tikz's `overlay, remember picture' anchors the
    drawing at the paper's own corner, so the two cannot disagree; the result
    is measured against the spec below and the build fails if it differs.
    """
    w, h = s["cover_width_in"], s["cover_height_in"]
    b, sp = s["bleed_in"], s["spine_width_in"]
    trim_w, trim_h = s["trim_width_in"], s["trim_height_in"]
    safe = s["safe_zone_in"]
    back_l, back_r = b, b + trim_w
    spine_l, spine_r = back_r, back_r + sp
    front_l, front_r = spine_r, spine_r + trim_w
    return rf"""%% GENERATED by tools/kdpcover.py -- do not edit.
%% Cover template for volume {s['volume']} ({s['language']}), {s['page_count']} pages.
%% Guides only: trim, bleed, spine and safe zone. Nothing here is artwork.
\documentclass{{article}}
\usepackage[paperwidth={w}in,paperheight={h}in,margin=0pt]{{geometry}}
\usepackage{{tikz}}
\usetikzlibrary{{calc}}
\pagestyle{{empty}}
\begin{{document}}
\begin{{tikzpicture}}[remember picture, overlay, x=1in, y=1in,
                     inner sep=0pt, outer sep=0pt]
  \coordinate (O) at (current page.south west);
  % bleed edge: the full artboard. Artwork must reach it.
  \draw[gray!55,dashed,line width=0.4pt] (O) rectangle ($(O)+({w},{h})$);
  \node[gray!55,font=\tiny,anchor=south west] at ($(O)+(0.04,0.04)$)
    {{bleed {b}in -- artwork must reach this edge}};
  % trim
  \draw[red!70,line width=0.6pt] ($(O)+({b},{b})$) rectangle ($(O)+({w - b},{h - b})$);
  \node[red!70,font=\tiny,anchor=south west] at ($(O)+({b + 0.04},{b + 0.05})$) {{trim}};
  % spine panel
  \draw[blue!70,line width=0.6pt]
    ($(O)+({spine_l},{b})$) rectangle ($(O)+({spine_r},{h - b})$);
  \node[blue!70,font=\tiny,rotate=90] at ($(O)+({(spine_l + spine_r) / 2},{h / 2})$)
    {{spine {sp}in ({s['page_count']} pp)}};
  % safe zones, inset from TRIM on each panel
  \draw[green!55!black,dotted,line width=0.5pt]
    ($(O)+({back_l + safe},{b + safe})$) rectangle ($(O)+({back_r - safe},{h - b - safe})$);
  \draw[green!55!black,dotted,line width=0.5pt]
    ($(O)+({front_l + safe},{b + safe})$) rectangle ($(O)+({front_r - safe},{h - b - safe})$);
  \node[green!55!black,font=\tiny,anchor=north west]
    at ($(O)+({back_l + safe + 0.04},{h - b - safe - 0.04})$) {{back cover, safe zone {safe}in}};
  \node[green!55!black,font=\tiny,anchor=north west]
    at ($(O)+({front_l + safe + 0.04},{h - b - safe - 0.04})$) {{front cover, safe zone {safe}in}};
  \node[gray,font=\tiny,anchor=north] at ($(O)+({w / 2},{h - 0.07})$)
    {{{w}in x {h}in -- volume {s['volume']} ({s['language']}), {s['page_count']} pages}};
\end{{tikzpicture}}
\mbox{{}}
\end{{document}}
"""


def build_template(s: dict, outdir: Path) -> bool:
    outdir.mkdir(parents=True, exist_ok=True)
    tex = outdir / "cover-template.tex"
    tex.write_text(template_tex(s), "utf8")
    r = subprocess.run(["pdflatex", "-interaction=batchmode",
                        f"-output-directory={outdir}", str(tex)],
                       capture_output=True, cwd=outdir)
    pdf = outdir / "cover-template.pdf"
    if r.returncode != 0 or not pdf.exists():
        return False
    # The template is only useful if it is the exact size it claims.
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    m = re.search(r"Page size:\s+([\d.]+) x ([\d.]+)", out)
    if not m:
        return False
    w_in, h_in = float(m.group(1)) / 72, float(m.group(2)) / 72
    s["template_measured_width_in"] = round(w_in, 4)
    s["template_measured_height_in"] = round(h_in, 4)
    # 0.01 in of slack would hide exactly the 0.0055 in error that
    # standalone[tightpage] introduced. Half a point is the tolerance.
    tol = 0.5 / 72
    ok = (abs(w_in - s["cover_width_in"]) < tol
          and abs(h_in - s["cover_height_in"]) < tol)
    s["template_size_ok"] = ok
    return ok


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pdfs", nargs="*")
    ap.add_argument("--all", action="store_true")
    a = ap.parse_args()

    cfg = json.loads((ROOT / "tools" / "volumes.json").read_text("utf8"))
    byn = {v["n"]: v for v in cfg["volumes"]}
    pdfs = ([STAGE / f"kdp-v{v['n']}-{l}.pdf" for v in cfg["volumes"]
             for l in ("en", "pl")] if a.all else [Path(p) for p in a.pdfs])
    if not pdfs:
        ap.error("give an interior PDF, or --all")

    rc = 0
    for pdf in pdfs:
        if not pdf.exists():
            print(f"  {pdf.name}: not built")
            rc = 1
            continue
        m = re.match(r"kdp-v(\d+)-(en|pl)", pdf.stem)
        if not m:
            print(f"  {pdf.name}: not a volume interior")
            rc = 1
            continue
        n, lang = int(m.group(1)), m.group(2)
        s = spec(pages_of(pdf), cfg, byn[n], lang, pdf)
        d = OUT / pdf.stem
        d.mkdir(parents=True, exist_ok=True)
        ok = build_template(s, d)
        (d / "cover-spec.json").write_text(json.dumps(s, indent=1), "utf8")
        flag = "" if s["spine_text_allowed"] else "  (TOO THIN FOR SPINE TEXT)"
        print(f"  v{n}-{lang}: {s['page_count']} pp, spine "
              f"{s['spine_width_in']} in, cover {s['cover_width_in']} x "
              f"{s['cover_height_in']} in{flag}")
        if not ok:
            print(f"    FAIL  cover-template.pdf is not the size it specifies")
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
