#!/usr/bin/env python3
r"""The page census the volume split is chosen from.

Builds the WHOLE book in the KDP geometry as one document, in both languages,
and reports the page count per part. A split can then be reasoned about before
any volume exists -- and re-derived when the book grows, rather than inherited
from whatever it was when the split was first drawn.

Part extents are differences between consecutive part folios in the .toc, so
they are correct whatever the front matter's length is; the front matter is
measured separately by finding the page that prints folio 1. CLAUDE.md records
a whole CI chase lost to reading a printed folio as a PDF page number, so the
two are never mixed here.

Run:  python3 tools/kdpcensus.py
      python3 tools/kdpcensus.py --pt 11      (compare a different body size)
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STAGE = ROOT / "build" / "kdp" / "tex"
OUT = ROOT / "build" / "kdp"
# Longest-first: 'IX'.startswith('I') is true, so a shorter numeral first would
# file Part IX under Part I -- which it did, on the first run of this.
ROMAN = ["VIII", "VII", "VI", "IV", "IX", "V", "III", "II", "I", "X"]

MAIN = r"""%% GENERATED by tools/kdpcensus.py -- a measurement, not a deliverable.
\documentclass[{pt}pt,twoside,openright]{{book}}
\def\booklang{{{lang}}}
\def\bookpaper{{standard}}
\def\mfavolume{{0}}
\input{{kdp/generated/volinfo-v1-{lang}}}
\input{{kdp/generated/voltitles-{lang}}}
\input{{kdp/preamble-kdp}}
\hypersetup{{pdftitle={{KDP census {lang} {pt}pt}}}}
\input{{body}}
"""


def parts_of(toc: Path):
    src = toc.read_text("utf8")
    raw = [(m.group(1), int(m.group(2))) for m in
           re.finditer(r"\\contentsline \{part\}\{(.*?)\}\{(\d+)\}", src)]
    last = max(int(m.group(1))
               for m in re.finditer(r"\}\{(\d+)\}\{[a-zA-Z]", src))
    out = {}
    for i, (lbl, f) in enumerate(raw):
        end = raw[i + 1][1] if i + 1 < len(raw) else last
        for r in ROMAN:
            if lbl.startswith(r):
                out[r] = end - f
                break
    return out


def front_matter(pdf: Path, partword: str) -> int | None:
    """The page that prints folio 1 is the Part I title; everything before it
    is front matter. Measured from the artefact rather than counted."""
    for p in range(10, 90):
        t = subprocess.run(["pdftotext", "-f", str(p), "-l", str(p), str(pdf), "-"],
                           capture_output=True, text=True).stdout
        if partword in t and len(t.split()) < 12:
            return p - 1
    return None


def run(lang: str, pt: int) -> dict | None:
    job = f"kdp-census-{lang}-{pt}"
    (STAGE / f"{job}.tex").write_text(MAIN.format(pt=pt, lang=lang), "utf8")
    r = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode",
                        "-file-line-error", f"-jobname={job}", f"{job}.tex"],
                       cwd=STAGE, capture_output=True)
    pdf = STAGE / f"{job}.pdf"
    if r.returncode != 0 or not pdf.exists():
        print(f"  {lang} {pt}pt: latexmk exit {r.returncode}")
        return None
    total = int(subprocess.run(["pdfinfo", str(pdf)], capture_output=True,
                               text=True).stdout.split("Pages:")[1].split()[0])
    word = "Foundation" if lang == "en" else "Podstawy"
    return {"lang": lang, "pt": pt, "total": total,
            "front": front_matter(pdf, word),
            "parts": parts_of(STAGE / f"{job}.toc")}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    cfg = json.loads((ROOT / "tools" / "volumes.json").read_text("utf8"))
    ap.add_argument("--pt", type=int, default=cfg["body_pt"])
    ap.add_argument("--langs", default="en,pl")
    a = ap.parse_args()

    res = [r for r in (run(l, a.pt) for l in a.langs.split(",")) if r]
    if not res:
        return 1
    order = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX"]
    print(f"\n  PAGE CENSUS -- {cfg['trim']['name']} in at {a.pt}pt")
    print(f"  {'Part':6}" + "".join(f"{r['lang']:>9}" for r in res))
    body = {r["lang"]: 0 for r in res}
    for p in order:
        line = f"  {p:6}"
        for r in res:
            v = r["parts"].get(p, 0)
            body[r["lang"]] += v
            line += f"{v:>9}"
        print(line)
    print(f"  {'body':6}" + "".join(f"{body[r['lang']]:>9}" for r in res))
    print(f"  {'front':6}" + "".join(f"{r['front'] or '?':>9}" for r in res))
    print(f"  {'TOTAL':6}" + "".join(f"{r['total']:>9}" for r in res))

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "page-census.json").write_text(json.dumps(
        {"trim": cfg["trim"]["name"], "pt": a.pt, "builds": res}, indent=1), "utf8")
    print(f"\n  wrote {(OUT / 'page-census.json').relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
